Day 3 -Numpy  + Linear Regression 

Assignment:

1.House Price Priduction

In [6]:
#Import Data
import numpy as np
house_size = np.array([600,750,850,1000,1100,1250,1400,1550,1700,1850])
badroom = np.array([1,2,2,2,3,3,3,4,4,4])
price = np.array([28,34,38,44,49,55,60,68,73,79])
print("House Size:", house_size)
print("Badroom:",badroom )
print("Price: ", price)

House Size: [ 600  750  850 1000 1100 1250 1400 1550 1700 1850]
Badroom: [1 2 2 2 3 3 3 4 4 4]
Price:  [28 34 38 44 49 55 60 68 73 79]


In [7]:
#Create Design Matrix
x = np.column_stack([np.ones(len(house_size)),house_size, badroom])
print("Design Matrix: ")
print(x)

Design Matrix: 
[[1.00e+00 6.00e+02 1.00e+00]
 [1.00e+00 7.50e+02 2.00e+00]
 [1.00e+00 8.50e+02 2.00e+00]
 [1.00e+00 1.00e+03 2.00e+00]
 [1.00e+00 1.10e+03 3.00e+00]
 [1.00e+00 1.25e+03 3.00e+00]
 [1.00e+00 1.40e+03 3.00e+00]
 [1.00e+00 1.55e+03 4.00e+00]
 [1.00e+00 1.70e+03 4.00e+00]
 [1.00e+00 1.85e+03 4.00e+00]]


In [8]:
#Calculate Beta (Normal equation)
beta = np.linalg.inv(x.T @ x) @ x.T @ price

print("Beta [intercept, house_size, badroom]:")
print(beta)

Beta [intercept, house_size, badroom]:
[3.29597593 0.03827003 1.21022941]


In [10]:
#Pridict New house Price
new_house = np.array([1, 1300, 3])
pridicted_price = new_house @ beta
print("Pridictied price for 1300 sq. ft., 3-badroom house:")
print(pridicted_price)

Pridictied price for 1300 sq. ft., 3-badroom house:
56.677698382851595


2.Single Feature Comparison

In [11]:
hours_studied = np.array([2 ,3, 4, 5, 6, 7, 8, 9, 10, 11])
practice_test = np.array([1,2,2,3,3,4,4,5,5,6])
exam_score = np.array([52, 60, 64, 71, 75, 82, 85, 91, 94, 99])

print("Hours Studied: ", hours_studied)
print("Practice Text: ",practice_test)
print("Exam Score:",exam_score)

Hours Studied:  [ 2  3  4  5  6  7  8  9 10 11]
Practice Text:  [1 2 2 3 3 4 4 5 5 6]
Exam Score: [52 60 64 71 75 82 85 91 94 99]


In [13]:
#Build Single Feature Model
x_single = np.column_stack([np.ones(len(hours_studied)),hours_studied])
beta_single = np.linalg.inv(x_single.T @ x_single) @ x_single.T @ exam_score
print("Beta [intercept,house_studied]:")
print(beta_single)

Beta [intercept,house_studied]:
[44.01212121  5.12121212]


In [14]:
#Pridictions:

predictions_single = x_single @ beta_single

print("Predictions: ", predictions_single)
print("\nActual:",exam_score)

Predictions:  [ 54.25454545  59.37575758  64.4969697   69.61818182  74.73939394
  79.86060606  84.98181818  90.1030303   95.22424242 100.34545455]

Actual: [52 60 64 71 75 82 85 91 94 99]


In [15]:
#Caalculate R sq 

ss_res = sum((exam_score - predictions_single) ** 2)
ss_tot = np.sum((exam_score - np.mean(exam_score)) ** 2)

r2_single = 1  - (ss_res / ss_tot)

print("R-Sq:",r2_single)

R-Sq: 0.9924829692271553


In [16]:
#3.Resusable Prediction Function

def predict(beta, *features):
    x = np.array([1, *features])
    return x @ beta

In [17]:
#Test Function
beta = np.array([43.55, 3.55, 3.05])

new_student_prediction = predict(beta, 6.5,3)

print("Predicted score: ",new_student_prediction)

Predicted score:  75.775


In [19]:
#4.Broadcasting Prectict

marks = np.array([
    [78, 42, 60],
    [55, 38, 70],
    [90, 45, 68],
    [63, 30, 55],
    [88, 48, 72]
])

max_marks= np.array([100,50,75])
print("Marks: ",marks)
print("\Max_marks: ",max_marks)

Marks:  [[78 42 60]
 [55 38 70]
 [90 45 68]
 [63 30 55]
 [88 48 72]]
\Max_marks:  [100  50  75]


In [21]:
ppercentage = marks / max_marks * 100

print("Percentage: ",ppercentage)
#No for loop is required because numoy automatically broadcasting max_marks across all 5 rows

Percentage:  [[78.         84.         80.        ]
 [55.         76.         93.33333333]
 [90.         90.         90.66666667]
 [63.         60.         73.33333333]
 [88.         96.         96.        ]]


In [22]:
#5.Verify Normal Equation using np.linalg.lstsq()

x_original = np.column_stack([np.ones(len(hours_studied)),hours_studied,practice_test])

y_original = exam_score

print("x:",x_original)
print("\ny",y_original)

x: [[ 1.  2.  1.]
 [ 1.  3.  2.]
 [ 1.  4.  2.]
 [ 1.  5.  3.]
 [ 1.  6.  3.]
 [ 1.  7.  4.]
 [ 1.  8.  4.]
 [ 1.  9.  5.]
 [ 1. 10.  5.]
 [ 1. 11.  6.]]

y [52 60 64 71 75 82 85 91 94 99]


In [24]:
#Normal Equation Beta
beta_normal = np.linalg.inv(x_original.T @ x_original) @ x_original.T @ y_original

print("Beta from Normal Equation: ",beta_normal)

Beta from Normal Equation:  [43.55  3.55  3.05]


In [27]:
#lataq()

beta_lstaq = np.linalg.lstsq(
    x_original,
    y_original,
    rcond = None
)[0]

print("Beta from np.lialg.lstsq(): ",beta_lstaq)

Beta from np.lialg.lstsq():  [43.55  3.55  3.05]


In [29]:
#Veryfing
result = np.allclose(beta_normal,beta_lstaq)

print("Do both methods match?")
print(result)

Do both methods match?
True
